### ISSUE TITLE
JetBrainsDark_DiffHighContrast.json: Background of the local branch indicator is not dark-theme aware

### ISSUE THREAD

**Issue by odalet** [sourcegit-scm/sourcegit-theme#3]
Since SourceGit v8.27, the background of the local branch badge in the git tree view is not very readable in dark mode. I guess this is because the background does not change when switching theme. 

Here is a before/after comparison (experienced both on Windows and Linux):

![image](https://github.com/user-attachments/assets/6d24ab52-cb9e-4bf8-a14d-e943a4083f50)

![image](https://github.com/user-attachments/assets/7e5df2ea-be3b-4820-92be-c11782b84c47)

I changed `DecoratorFG` from `#ffffff` to `#000000` and it looks better; however, I'm not sure this is really the way to go (the same change would also benefit `JetBrainsDark.json` by the way).

**Comment by love-linger** [comment]
anthor key `DecoratorHead` was added for current head decorator background

**Comment by love-linger** [comment]
JUST a tip: now we use reverted foreground for REF decorators. For exmple, the built-in theme:

![image](https://github.com/user-attachments/assets/366b9648-de99-4b42-9b22-d32fff5d0801)
![image](https://github.com/user-attachments/assets/a1b2c89c-1517-4aed-b04a-2ae2fd48677b)

We use `White` on light theme and `Black` on dark theme for REF decorators.

**Comment by odalet** [comment]
Thanks for the tip. I ended up defining this (so that it looks like the built-in dark theme):

```json
    "DecoratorFG": "#000000",
    "DecoratorHead": "#f4f1de"
```

I think it loks quite nice:

![image](https://github.com/user-attachments/assets/213eca7e-bbfd-47ec-96d3-9a3cd88f2f68)

Would you like me to submit a PR with these changes to `JetBrainsDark.json` and `JetBrainsDark_DiffHighContrast.json`?
